[package]
name = "Cybersecurity-Machine-Learning"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
libc = "0.2.162"
pcap = "2.2.0"
pnet = "0.35.0"
paste = "1.0.15"
strum_macros = "0.26.4"
strum = "0.26.3"
tokio = { version = "1", features = ["full"] }